# -*- coding: utf-8 -*-
"""set_up_db.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EoVusmE0atI8fXqebApp9FuVRGoYQf70
"""

import pymongo
import time
from pymongo import IndexModel, ASCENDING, DESCENDING

print(time.ctime())
myclient = pymongo.MongoClient('mongodb://localhost:27017/')
# myclient = pymongo.MongoClient('localhost',27017)
# myclient = pymongo.MongoClient('mongodb://127.0.0.1:27017')


mydb = myclient['covid-stigma21']

mylist = [] # a list of collection names
for i in range(len(mylist)):
    mycol = mydb[mylist[i]]
    id_ = IndexModel([('id', ASCENDING)], unique=True)
    lang = IndexModel([('lang', ASCENDING)])
    user_id = IndexModel([('user.id', ASCENDING)])
    created_at = IndexModel([('created_at', ASCENDING)])
    mycol.create_indexes([id_, lang, user_id, created_at])

print(time.ctime())